const proverbs = [

{id:1, proverb:"A bad carpenter quarrels with his tools."},
{id:2, proverb:"A bird in the hand is worth two in the bush."},
{id:3, proverb:"A burnt child dreads the fire."},
{id:4, proverb:"A drowning man catches at a straw."},
{id:5, proverb:"A friend in need is a friend indeed."},
{id:6, proverb:"A little learning is a dangerous thing."},
{id:7, proverb:"A man is known by the company he keeps."},
{id:8, proverb:"A rolling stone gathers no moss."},
{id:9, proverb:"A stitch in time saves nine."},
{id:10, proverb:"Absence makes the heart grow fonder."},

{id:11, proverb:"Actions speak louder than words."},
{id:12, proverb:"All that glitters is not gold."},
{id:13, proverb:"All's well that ends well."},
{id:14, proverb:"An idle brain is the devil's workshop."},
{id:15, proverb:"As you sow, so shall you reap."},
{id:16, proverb:"Barking dogs seldom bite."},
{id:17, proverb:"Beauty is only skin deep."},
{id:18, proverb:"Beggars cannot be choosers."},
{id:19, proverb:"Better late than never."},
{id:20, proverb:"Better safe than sorry."},

{id:21, proverb:"Birds of a feather flock together."},
{id:22, proverb:"Charity begins at home."},
{id:23, proverb:"Cleanliness is next to godliness."},
{id:24, proverb:"Cut your coat according to your cloth."},
{id:25, proverb:"Desperate diseases need desperate remedies."},
{id:26, proverb:"Do not cry over spilt milk."},
{id:27, proverb:"Don't count your chickens before they hatch."},
{id:28, proverb:"Easy come, easy go."},
{id:29, proverb:"Empty vessels make much noise."},
{id:30, proverb:"Every cloud has a silver lining."},

{id:31, proverb:"Every dog has its day."},
{id:32, proverb:"Experience is the best teacher."},
{id:33, proverb:"Failure is the pillar of success."},
{id:34, proverb:"First deserve, then desire."},
{id:35, proverb:"Fortune favors the brave."},
{id:36, proverb:"God helps those who help themselves."},
{id:37, proverb:"Grasp all, lose all."},
{id:38, proverb:"Half a loaf is better than none."},
{id:39, proverb:"Haste makes waste."},
{id:40, proverb:"Health is wealth."},

{id:41, proverb:"He laughs best who laughs last."},
{id:42, proverb:"Honesty is the best policy."},
{id:43, proverb:"Hope for the best and prepare for the worst."},
{id:44, proverb:"If wishes were horses, beggars would ride."},
{id:45, proverb:"It is never too late to mend."},
{id:46, proverb:"Jack of all trades, master of none."},
{id:47, proverb:"Knowledge is power."},
{id:48, proverb:"Least said, soonest mended."},
{id:49, proverb:"Let bygones be bygones."},
{id:50, proverb:"Little drops of water make a mighty ocean."},
{id:51, proverb:"Little knowledge is a dangerous thing."},
{id:52, proverb:"Look before you leap."},
{id:53, proverb:"Love begets love."},
{id:54, proverb:"Make hay while the sun shines."},
{id:55, proverb:"Man proposes, God disposes."},
{id:56, proverb:"Many hands make light work."},
{id:57, proverb:"Might is right."},
{id:58, proverb:"Misfortunes never come singly."},
{id:59, proverb:"Money begets money."},
{id:60, proverb:"Necessity is the mother of invention."},

{id:61, proverb:"Necessity knows no law."},
{id:62, proverb:"No gains without pains."},
{id:63, proverb:"No rose without a thorn."},
{id:64, proverb:"Old is gold."},
{id:65, proverb:"Once bitten, twice shy."},
{id:66, proverb:"One good turn deserves another."},
{id:67, proverb:"One swallow does not make a summer."},
{id:68, proverb:"Out of sight, out of mind."},
{id:69, proverb:"Penny wise and pound foolish."},
{id:70, proverb:"Practice makes a man perfect."},

{id:71, proverb:"Prevention is better than cure."},
{id:72, proverb:"Rome was not built in a day."},
{id:73, proverb:"Seeing is believing."},
{id:74, proverb:"Slow and steady wins the race."},
{id:75, proverb:"Speech is silver; silence is golden."},
{id:76, proverb:"Still waters run deep."},
{id:77, proverb:"Strike while the iron is hot."},
{id:78, proverb:"The early bird catches the worm."},
{id:79, proverb:"The end justifies the means."},
{id:80, proverb:"The face is the index of the mind."},

{id:81, proverb:"The pen is mightier than the sword."},
{id:82, proverb:"There is no smoke without fire."},
{id:83, proverb:"There is no rose without a thorn."},
{id:84, proverb:"Time and tide wait for none."},
{id:85, proverb:"To err is human; to forgive is divine."},
{id:86, proverb:"Too many cooks spoil the broth."},
{id:87, proverb:"Truth always triumphs."},
{id:88, proverb:"United we stand, divided we fall."},
{id:89, proverb:"Waste not, want not."},
{id:90, proverb:"Well begun is half done."},

{id:91, proverb:"Where there is a will, there is a way."},
{id:92, proverb:"While there is life, there is hope."},
{id:93, proverb:"You cannot serve two masters."},
{id:94, proverb:"Youth will be served."},
{id:95, proverb:"Virtue is its own reward."},
{id:96, proverb:"Walls have ears."},
{id:97, proverb:"Think before you speak."},
{id:98, proverb:"The more you read, the more you know."},
{id:99, proverb:"Time is the best healer."},
{id:100, proverb:"United we achieve more."},
{id:101, proverb:"A chain is no stronger than its weakest link."},
{id:102, proverb:"A contented mind is a continual feast."},
{id:103, proverb:"A fool and his money are soon parted."},
{id:104, proverb:"A hungry man is an angry man."},
{id:105, proverb:"A leopard cannot change its spots."},
{id:106, proverb:"A miss is as good as a mile."},
{id:107, proverb:"A penny saved is a penny earned."},
{id:108, proverb:"A tree is known by its fruit."},
{id:109, proverb:"Adversity is the touchstone of character."},
{id:110, proverb:"All roads lead to Rome."},

{id:111, proverb:"All work and no play makes Jack a dull boy."},
{id:112, proverb:"An empty sack cannot stand upright."},
{id:113, proverb:"Appearances are often deceptive."},
{id:114, proverb:"Bad news travels fast."},
{id:115, proverb:"Better bend than break."},
{id:116, proverb:"Better die than live dishonestly."},
{id:117, proverb:"Better wear out than rust out."},
{id:118, proverb:"Blood is thicker than water."},
{id:119, proverb:"Cowards die many times before their death."},
{id:120, proverb:"Custom is a second nature."},

{id:121, proverb:"Death keeps no calendar."},
{id:122, proverb:"Diamond cuts diamond."},
{id:123, proverb:"Divide and rule."},
{id:124, proverb:"Do evil and look for the like."},
{id:125, proverb:"Do not put the cart before the horse."},
{id:126, proverb:"Do unto others as you would have them do unto you."},
{id:127, proverb:"Every man has his price."},
{id:128, proverb:"Every man is the architect of his own fortune."},
{id:129, proverb:"Example is better than precept."},
{id:130, proverb:"Experience is the mother of wisdom."},

{id:131, proverb:"Forbidden fruit is sweetest."},
{id:132, proverb:"Forgive and forget."},
{id:133, proverb:"Give honor where honor is due."},
{id:134, proverb:"Good wine needs no bush."},
{id:135, proverb:"Habit is second nature."},
{id:136, proverb:"Handsome is that handsome does."},
{id:137, proverb:"Hope is the balm of life."},
{id:138, proverb:"Ignorance is bliss."},
{id:139, proverb:"In unity there is strength."},
{id:140, proverb:"It never rains but it pours."},

{id:141, proverb:"Justice delayed is justice denied."},
{id:142, proverb:"Keep your mouth shut and your eyes open."},
{id:143, proverb:"Learn to walk before you run."},
{id:144, proverb:"Life is not a bed of roses."},
{id:145, proverb:"Live and let live."},
{id:146, proverb:"Money is the root of all evil."},
{id:147, proverb:"No man can serve two masters."},
{id:148, proverb:"No one can make you feel inferior without your consent."},
{id:149, proverb:"Pride goes before a fall."},
{id:150, proverb:"United we stand, divided we fall."}

];