const proverbs = [

{ id:1, proverb:"A stitch in time saves nine." },
{ id:2, proverb:"Time and tide wait for none." },
{ id:3, proverb:"Where there is a will, there is a way." },
{ id:4, proverb:"Honesty is the best policy." },
{ id:5, proverb:"Knowledge is power." },
{ id:6, proverb:"Practice makes a man perfect." },
{ id:7, proverb:"No pain, no gain." },
{ id:8, proverb:"Look before you leap." },
{ id:9, proverb:"Slow and steady wins the race." },
{ id:10, proverb:"United we stand, divided we fall." },

{ id:11, proverb:"All that glitters is not gold." },
{ id:12, proverb:"A friend in need is a friend indeed." },
{ id:13, proverb:"Actions speak louder than words." },
{ id:14, proverb:"An idle brain is the devil's workshop." },
{ id:15, proverb:"As you sow, so shall you reap." },
{ id:16, proverb:"Barking dogs seldom bite." },
{ id:17, proverb:"Better late than never." },
{ id:18, proverb:"Better safe than sorry." },
{ id:19, proverb:"Birds of a feather flock together." },
{ id:20, proverb:"Charity begins at home." },

{ id:21, proverb:"Cut your coat according to your cloth." },
{ id:22, proverb:"Don't count your chickens before they hatch." },
{ id:23, proverb:"Easy come, easy go." },
{ id:24, proverb:"Empty vessels make much noise." },
{ id:25, proverb:"Every cloud has a silver lining." },
{ id:26, proverb:"Experience is the best teacher." },
{ id:27, proverb:"Failure is the pillar of success." },
{ id:28, proverb:"First deserve, then desire." },
{ id:29, proverb:"Fortune favors the brave." },
{ id:30, proverb:"Health is wealth." },

{ id:31, proverb:"Half a loaf is better than none." },
{ id:32, proverb:"Haste makes waste." },
{ id:33, proverb:"Hope for the best, prepare for the worst." },
{ id:34, proverb:"If wishes were horses, beggars would ride." },
{ id:35, proverb:"It is never too late to mend." },
{ id:36, proverb:"Justice delayed is justice denied." },
{ id:37, proverb:"Keep your mouth shut and your eyes open." },
{ id:38, proverb:"Little drops of water make a mighty ocean." },
{ id:39, proverb:"Little knowledge is a dangerous thing." },
{ id:40, proverb:"Live and let live." },

{ id:41, proverb:"Make hay while the sun shines." },
{ id:42, proverb:"Man proposes, God disposes." },
{ id:43, proverb:"Many hands make light work." },
{ id:44, proverb:"Money cannot buy happiness." },
{ id:45, proverb:"Necessity is the mother of invention." },
{ id:46, proverb:"Never put off till tomorrow what you can do today." },
{ id:47, proverb:"No rose without a thorn." },
{ id:48, proverb:"Old is gold." },
{ id:49, proverb:"One swallow does not make a summer." },
{ id:50, proverb:"Penny wise and pound foolish." },

{ id:51, proverb:"Prevention is better than cure." },
{ id:52, proverb:"Rome was not built in a day." },
{ id:53, proverb:"Still waters run deep." },
{ id:54, proverb:"Strike while the iron is hot." },
{ id:55, proverb:"The early bird catches the worm." },
{ id:56, proverb:"The pen is mightier than the sword." },
{ id:57, proverb:"The proof of the pudding is in the eating." },
{ id:58, proverb:"The more you read, the more you know." },
{ id:59, proverb:"There is no smoke without fire." },
{ id:60, proverb:"To err is human; to forgive is divine." },

{ id:61, proverb:"Too many cooks spoil the broth." },
{ id:62, proverb:"Truth always triumphs." },
{ id:63, proverb:"United we stand, divided we fall." },
{ id:64, proverb:"Waste not, want not." },
{ id:65, proverb:"Well begun is half done." },
{ id:66, proverb:"When in Rome, do as the Romans do." },
{ id:67, proverb:"Where ignorance is bliss, it is folly to be wise." },
{ id:68, proverb:"While there is life, there is hope." },
{ id:69, proverb:"You cannot serve two masters." },
{ id:70, proverb:"A rolling stone gathers no moss." },

{ id:71, proverb:"A burnt child dreads the fire." },
{ id:72, proverb:"A little learning is a dangerous thing." },
{ id:73, proverb:"Beauty is only skin deep." },
{ id:74, proverb:"Blood is thicker than water." },
{ id:75, proverb:"Cleanliness is next to godliness." },
{ id:76, proverb:"Courtesy costs nothing." },
{ id:77, proverb:"Don't judge a book by its cover." },
{ id:78, proverb:"Every dog has its day." },
{ id:79, proverb:"God helps those who help themselves." },
{ id:80, proverb:"Great minds think alike." },

{ id:81, proverb:"Habit is second nature." },
{ id:82, proverb:"Handsome is that handsome does." },
{ id:83, proverb:"Learn to walk before you run." },
{ id:84, proverb:"Love begets love." },
{ id:85, proverb:"Misfortunes never come singly." },
{ id:86, proverb:"Necessity knows no law." },
{ id:87, proverb:"No gains without pains." },
{ id:88, proverb:"One good turn deserves another." },
{ id:89, proverb:"Out of sight, out of mind." },
{ id:90, proverb:"Seeing is believing." },

{ id:91, proverb:"Speech is silver, silence is golden." },
{ id:92, proverb:"The end justifies the means." },
{ id:93, proverb:"The face is the index of the mind." },
{ id:94, proverb:"The grass is always greener on the other side." },
{ id:95, proverb:"The more, the merrier." },
{ id:96, proverb:"There is no place like home." },
{ id:97, proverb:"Think before you speak." },
{ id:98, proverb:"United we achieve more." },
{ id:99, proverb:"Variety is the spice of life." },
{ id:100, proverb:"Walls have ears." }

];